/// <reference path="../../node_modules/angular2/typings/browser.d.ts" />
"use strict";
var browser_1 = require('angular2/platform/browser');
var http_1 = require('angular2/http');
var cliente_cmp_1 = require('./cliente/components/cliente-cmp');
var user_cmp_1 = require('./user/components/user-cmp');
var userlist_cmp_1 = require('./user/components/userlist-cmp');
var almacen_cmp_1 = require('./almacen/components/almacen-cmp');
var almacenlist_cmp_1 = require('./almacen/components/almacenlist-cmp');
var login_cmp_1 = require('./login/components/login-cmp');
var home_cmp_1 = require('./login/components/home-cmp');
var app_1 = require('./login/app');
browser_1.bootstrap(cliente_cmp_1.ClienteCmp, [http_1.HTTP_PROVIDERS]);
browser_1.bootstrap(user_cmp_1.UserCmp, [http_1.HTTP_PROVIDERS]);
browser_1.bootstrap(userlist_cmp_1.UserListCmp, [http_1.HTTP_PROVIDERS]);
browser_1.bootstrap(almacen_cmp_1.AlmacenCmp, [http_1.HTTP_PROVIDERS]);
browser_1.bootstrap(almacenlist_cmp_1.AlmacenListCmp, [http_1.HTTP_PROVIDERS]);
browser_1.bootstrap(login_cmp_1.LoginCmp, [http_1.HTTP_PROVIDERS]);
browser_1.bootstrap(home_cmp_1.HomeCmp, [http_1.HTTP_PROVIDERS]);
browser_1.bootstrap(app_1.App, [http_1.HTTP_PROVIDERS]);
